# Generated by Django 5.0.3 on 2024-10-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
