# Generated by Django 5.0.3 on 2024-10-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionregistration',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
